name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'dbt_sqlite'

#model-paths: ["models"]
#source-paths: ["models"]
#seed-paths: ["seeds"]
#data-paths: ["seeds"]
#test-paths: ["tests"]
#source-paths: []
#model-paths: []
#analysis-paths: ["analysis"]
#macro-paths: ["macros"]

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
#data-paths: ["data"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view
